name: 🚀 Deploy to cPanel
on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      # Step 2: Set up PHP and Composer
      - name: Set up PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3" # Adjust PHP version as per your Laravel requirements
          tools: "composer"

      # Step 3: Install PHP dependencies
      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      # Step 4: Install Node.js and npm dependencies (if your Laravel project has frontend assets)
      - name: Install Node.js and npm dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Adjust the Node.js version as per your project requirements

      - name: Install npm dependencies
        run: npm install # Installs npm dependencies (Laravel Mix or other frontend dependencies)

      # Step 5: Build frontend assets
      - name: Build frontend assets
        run: npm run prod # Adjust this to 'npm run dev' or another command if needed

      # Step 6: FTP deploy to cPanel
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # local-dir: ./  # Ensure this points to the correct directory
          # server-dir: /public_html/your-project-folder/  # Adjust this as needed for your server
          exclude: |
            .git/*
            node_modules/*
            .env
            .gitignore
            *.log  # Optional, exclude unnecessary files
